FROM ros:humble-ros-base

ENV DEBIAN_FRONTEND=noninteractive

# 安装编译和运行时依赖
RUN apt-get update && apt-get install -y \
    net-tools \
    openssh-client \
    openssh-server \
    file \
    iputils-ping \
    python3-pip \
    git \
    cmake \
    libopencv-dev \
    libssl-dev \
    libyaml-cpp-dev \
    ffmpeg \
    pybind11-dev \
    && pip3 install colcon-common-extensions nanobind numpy opencv-python -i https://pypi.tuna.tsinghua.edu.cn/simple \
    && rm -rf /var/lib/apt/lists/*

RUN wget -q --show-progress https://github.com/microsoft/onnxruntime/releases/download/v1.18.0/onnxruntime-linux-x64-1.18.0.tgz -O /tmp/onnxruntime.tgz && \
    tar -xzf /tmp/onnxruntime.tgz -C /usr/local/ && \
    mv /usr/local/onnxruntime-linux-x64-1.18.0 /usr/local/onnxruntime && \
    echo '/usr/local/onnxruntime/lib' > /etc/ld.so.conf.d/onnxruntime.conf && \
    ldconfig && \
    rm /tmp/onnxruntime.tgz
